name: Proxy Updater

on:
  push:
    branches:
      - main

jobs:
  update_proxies:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment (if needed)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install required dependencies (if applicable)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Add a custom script for proxy handling (or other tasks)
      - name: Fetch proxies and generate PAC files
        run: |
          # Fetch the proxy data (add your script or commands here)
          echo "Simulating proxy file generation..."

      # Step 5: Create or modify the proxy files (replace with your specific logic)
      - name: Create proxy files
        run: |
          echo "Creating proxy files..."
          echo "Proxy data for testing" > proxies.txt
          echo "Proxy data for France" > france_proxies.txt

      # Step 6: Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Push the changes using the built-in GITHUB_TOKEN
          git add *.txt
          git commit -m "Update proxies $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin "${{ github.ref }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 7: Clean up (optional)
      - name: Clean up old proxy files
        run: |
          find . -maxdepth 1 -type f -name "*.txt" ! -name "raw_*.txt" ! -name "proxies.txt" -delete
