name: Proxy Updater

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download https proxies
        run: curl -o raw_https.txt https://raw.githubusercontent.com/zloi-user/hideip.me/refs/heads/master/https.txt

      - name: Download connect proxies
        run: curl -o raw_connect.txt https://raw.githubusercontent.com/zloi-user/hideip.me/refs/heads/master/connect.txt

      - name: Process proxies
        run: |
          # Clean old country files but keep raw files and proxies.txt
          find . -maxdepth 1 -type f -name "*.txt" -not -name "raw_*.txt" -not -name "proxies.txt" -delete

          # Merge both raw files
          cat raw_https.txt raw_connect.txt > combined_raw.txt

          # Generate proxies.txt
          awk -F':' '{ printf "http://%s:%s/#%s\n", $1, $2, toupper(gensub(/ /,"","g",$3)) NR }' combined_raw.txt > proxies.txt

          # Split by country into country.txt files
          awk -F':' '
            {
              country=tolower($3)
              gsub(/ /, "-", country)
              count[country]++
              printf "http://%s:%s/#%s%d\n", $1, $2, toupper(country), count[country] >> country ".txt"
            }
          ' combined_raw.txt

      - name: Generate PAC files
        run: |
          for file in *.txt; do
            [[ "$file" == raw_* || "$file" == "proxies.txt" ]] && continue
            country="${file%.txt}"
            pacfile="${country}.pac"
            echo "var _0x2197=['...your_obfuscated_content_here...']; function FindProxyForURL(u,h){return 'PROXY example.com:8080';}" > "$pacfile"
          done

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Updated proxies and PAC files" || exit 0
          git push
