name: Proxy Updater

on:
  schedule:
    - cron: '0 * * * *'  # runs every hour
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download France proxies
        run: curl -o raw_france.txt https://raw.githubusercontent.com/goofingaround/proxy-updater/refs/heads/main/france.txt

      - name: Download UK proxies
        run: curl -o raw_united-kingdom.txt https://raw.githubusercontent.com/goofingaround/proxy-updater/refs/heads/main/united-kingdom.txt

      - name: Download connect.txt proxies
        run: curl -o raw_connect.txt https://github.com/zloi-user/hideip.me/raw/refs/heads/master/connect.txt

      - name: Clean old country files but keep raw files and proxies.txt
        run: find . -maxdepth 1 -type f -name "*.txt" ! -name "raw_*.txt" ! -name "proxies.txt" -delete

      - name: Process proxies for France
        run: |
          i=1
          grep -v '^$' raw_france.txt | while read proxy; do
            country_file="france_${i}.txt"
            echo "$proxy" >> "$country_file"
            i=$((i+1))
          done

      - name: Process proxies for UK
        run: |
          i=1
          grep -v '^$' raw_united-kingdom.txt | while read proxy; do
            country_file="united-kingdom_${i}.txt"
            echo "$proxy" >> "$country_file"
            i=$((i+1))
          done

      - name: Process proxies for connect.txt
        run: |
          i=1
          grep -v '^$' raw_connect.txt | while read proxy; do
            country_file="@@@_${i}.txt"
            echo "$proxy" >> "$country_file"
            i=$((i+1))
          done

      - name: Keep the combined proxies.txt
        run: cat raw_france.txt raw_united-kingdom.txt raw_connect.txt > proxies.txt

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.txt
          git commit -m "Update proxies $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
