name: Proxy Updater

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch proxy list (https)
        run: |
          curl -sL https://github.com/clarketm/proxy-list/raw/master/proxy-list-raw.txt -o raw_https.txt

      - name: Fetch proxy list (connect)
        run: |
          curl -sL https://github.com/zloi-user/hideip.me/raw/refs/heads/master/connect.txt -o raw_connect.txt

      - name: Clean old country files but keep raw files and proxies.txt
        run: |
          find . -maxdepth 1 -type f -name "*.txt" ! -name "raw_*.txt" ! -name "proxies.txt" -delete

      - name: Merge and process proxies
        run: |
          # Merge both raw files
          cat raw_https.txt raw_connect.txt > combined_raw.txt

          # Create proxies.txt with format http://IP:PORT/#COUNTRY
          awk -F':' '{
            country = tolower($3)
            gsub(/ /, "-", country)
            printf "http://%s:%s/#%s%d\n", $1, $2, toupper(country), NR
          }' combined_raw.txt > proxies.txt

          # Split into country-specific files
          awk -F':' '
            {
              country = tolower($3)
              gsub(/ /, "-", country)
              count[country]++
              printf "http://%s:%s/#%s%d\n", $1, $2, toupper(country), count[country] >> country ".txt"
            }
          ' combined_raw.txt

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.txt
          git commit -m "Automated update of proxies.txt and country files"
          git push
