name: Update Proxies

# Grant the workflow permission to commit & push back to the repo
permissions:
  contents: write

on:
  # Run on every push to main (so you can test instantly)
  push:
    branches:
      - main
  # Also run every 10 minutes
  schedule:
    - cron: '*/10 * * * *'
  # Allow manual trigger from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Fetch and reformat proxies
        run: |
          RAW="https://raw.githubusercontent.com/zloi-user/hideip.me/refs/heads/master/https.txt"
          curl -s "$RAW" \
            | while IFS=':' read -r ip port country; do
                # uppercase and replace spaces with hyphens for country
                C=$(echo "$country" | tr '[:lower:] ' '[:upper:]-')
                echo "http://${ip}:${port}/#${C}1"
              done \
            > proxies.txt

          echo "---- proxies.txt content ----"
          cat proxies.txt

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add proxies.txt
          # Only commit if there are changes
          git diff --cached --quiet || (git commit -m "Automated update of proxies.txt" && git push)
