name: Update Proxies

# Allow the Action to write back to your repo
permissions:
  contents: write

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Fetch raw list
        run: |
          RAW_URL="https://raw.githubusercontent.com/zloi-user/hideip.me/refs/heads/master/https.txt"
          curl -s "$RAW_URL" > raw.txt

      - name: Build combined proxies.txt
        run: |
          awk -F':' '{
            country=toupper($3); gsub(/ /,"-",country);
            print "http://" $1 ":" $2 "/#" country "1";
          }' raw.txt > proxies.txt

      - name: Split out per-country files
        shell: bash
        run: |
          # 1) Remove old country files (ignore errors if none exist)
          find . -maxdepth 1 -type f -name "*.txt" ! -name raw.txt ! -name proxies.txt -delete || true

          # 2) Use awk to group & number
          awk -F':' '
          BEGIN { OFS=""; }
          {
            # Normalize country for tag and filename
            tag = toupper($3); gsub(/ /, "-", tag);
            fname = tolower($3); gsub(/ /, "-", fname); fname = fname ".txt";
            # Increment counter
            count[tag]++;
            # Print into the per-country file
            print "http://"$1":"$2"/#"tag count[tag] >> fname;
          }
          ' raw.txt

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add proxies.txt
          git add *.txt
          git diff --cached --quiet || (git commit -m "Automated update of proxies (combined + per-country)" && git push)
